name = "time-tracker"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "time-tracker"
database_id = "ab08235e-ea6d-4442-afac-5e6fa9ee9809"

[vars]
NUXT_API_BASE_URL = "https://pixel-time-tracker.pages.dev"
